name: Test Python Package

on:
  push:
    branches: [ develop, feature/**, release/**, hotfix/** ]
  pull_request:
    branches: [ develop, feature/**, release/**, hotfix/** ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Test setup & install
      run: |
        poetry build
        python3 -m pip install dist/*.whl
    - name: Test run
      run: |
        gitlab-watchman --version
        gitlab-watchman --help